USE VF_POSTPAID;


set mapred.job.name = PAR_EXP_LOYALTY_LIN;
DROP TABLE VF_POSTPAID.PAR_EXP_LOYALTY_LIN;
CREATE TABLE VF_POSTPAID.PAR_EXP_LOYALTY_LIN 
AS SELECT TELEFONO AS MSISDN, MAX(CAST(REMAINNINGBINDING AS DOUBLE)) AS NUM_PERMANENCIA
FROM INPUT.VF_POS_PRD_LOYALTY_MSISDN 
WHERE PARTITIONED_MONTH =  '${hiveconf:MONTH0}' GROUP BY TELEFONO;

EXIT;
