configs:
  config_1:
    enabled: True
    start_port: 20181015
    end_port: 20181114
    closing_day: 20181014
    ccc_days: -60
    agg_by: msisdn
    save_car: True
    labeled: True
    model_target: comercial
    new_car_version: False
  config_2:
    enabled: True
    start_port: 20181008
    end_port: 20181107
    closing_day: 20181007
    ccc_days: -60
    agg_by: msisdn
    save_car: True
    labeled: True
    model_target: comercial
    new_car_version: False
