
# List of columns to be used in the model
FEATS_COLS = []

CATEGORICAL_COLS = None # None means the code detect them automatically  #FIXME autodetect with metadata project
NON_INFO_COLS = ["num_cliente"] #FIXME autodetect with metadata project
OWNER_LOGIN = "csanc109"






###################################################################################################
# MYVF APP
##################################################################################################


MODEL_OUTPUT_NAME_HIGH_POTENTIAL = "price_sens_high_potential"
MODEL_OUTPUT_NAME_GLOBAL_POTENTIAL_CLASSIF = "price_sens_glob_pot_classifier"




EXTRA_INFO_COLS = []
INSERT_TOP_K = None

HIGH_CORRELATED_VARS = []


# Var to Keep - extracted from log price_sens_newprod_20190731_20190831_mobile_0_24_eval_rf_class5_lab3_20200528_212241.log
# Keep top300 of RF + feature_selection_correlation(df, cols_to_filter, threshold=0.8, label_col = 'label', pcg = 1.0)
VERSION_10_VARS = ['Bill_N3_InvoiceCharges',
 'Ord_sla_last_order_last60',
 'Bill_N4_Tax_Amount',
 'netscout_ns_apps_spotify_days_agg_mean',
 'Bill_L2_N1_N4_Amount_To_Pay',
 'Cust_CICLO',
 'netscout_ns_apps_finance_data_mb_agg_mean',
 'GNV_Data_L2_total_data_volume_agg_mean',
 'Ord_sla_ord_admin_first_order_last30',
 'Ord_sla_first_order_last30',
 'netscout_ns_apps_itunes_total_effective_dl_mb_agg_mean',
 'Cust_Agg_L2_mobile_fx_first_days_since_nc',
 'netscout_ns_apps_shopping_data_mb_agg_mean',
 'netscout_ns_apps_instagram_timestamps_agg_mean',
 'Cust_Agg_bam_services_nif',
 'netscout_ns_apps_business_total_effective_ul_mb_agg_mean',
 'Ord_sla_nb_started_orders_last90',
 'netscout_ns_apps_technology_data_mb_agg_mean',
 'Cust_Agg_fixed_services_nif',
 'netscout_ns_apps_facebook_data_mb_agg_mean',
 'Bill_L2_N2_N3_Amount_To_Pay',
 'Penal_SRV_FINISHED_N5_days_to_agg_mean',
 'Ord_sla_first_order_last365',
 'Cust_Agg_L2_bam_fx_first_days_since_nc',
 'netscout_ns_apps_facebook_total_effective_dl_mb_agg_mean',
 'Bill_L2_N1_N3_Amount_To_Pay',
 'tgs_days_until_f_fin_bi_agg_mean',
 'Cust_Agg_num_tariff_otros',
 'Cust_L2_days_until_next_bill',
 'Cust_Agg_tv_services_nc',
 'netscout_ns_apps_whatsapp_days_agg_mean',
 'netscout_ns_apps_whatsapp_voice_calling_timestamps_agg_mean',
 'netscout_ns_apps_googlemaps_total_effective_ul_mb_agg_mean',
 'Bill_L2_N1_N5_Amount_To_Pay',
 'netscout_ns_apps_web_vodafone_http_data_mb_agg_mean',
 'netscout_ns_apps_netflix_total_effective_dl_mb_agg_mean',
 'GNV_Voice_L2_max_mou_per_call_WE_agg_mean',
 'Bill_L2_n4_n5_net',
 'tgs_has_discount_agg_mean',
 'netscout_ns_apps_snapchat_total_effective_dl_mb_agg_mean',
 'netscout_ns_apps_technology_total_effective_dl_mb_agg_mean',
 'netscout_ns_apps_snapchat_timestamps_agg_mean',
 'netscout_ns_apps_samsung_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_facebookmessages_timestamps_agg_mean',
 'netscout_ns_apps_googleplay_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_booking_total_effective_dl_mb_agg_mean',
 'netscout_ns_apps_facebookmessages_data_mb_agg_mean',
 'Cust_birth_date',
 'netscout_ns_apps_adultweb_timestamps_agg_mean',
 'Ord_sla_ord_admin_first_order_last365',
 'GNV_Data_L2_total_connections_W_agg_mean',
 'netscout_ns_apps_youtube_timestamps_agg_mean',
 'netscout_ns_apps_audio_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_shopping_timestamps_agg_mean',
 'netscout_ns_apps_googlemaps_total_effective_dl_mb_agg_mean',
 'Bill_L2_n1_n2_net',
 'GNV_Data_L2_max_connections_WE_agg_mean',
 'tgs_sum_ind_over_use_agg_mean',
 'netscout_ns_apps_twitter_total_effective_dl_mb_agg_mean',
 'tgs_days_since_f_inicio_bi_agg_mean',
 'Ord_sla_first_order_last180',
 'netscout_ns_apps_whatsapp_total_effective_ul_mb_agg_mean',
 'Ord_sla_last_order_last90',
 'Ord_sla_last_order_last120',
 'netscout_ns_apps_facebookmessages_days_agg_mean',
 'Cust_Agg_L2_fixed_fx_first_days_since_nc',
 'netscout_ns_apps_googleplay_total_effective_dl_mb_agg_mean',
 'GNV_Voice_L2_max_mou_per_call_W_agg_mean',
 'GNV_Data_L2_max_connections_W_agg_mean',
 'netscout_ns_apps_snapchat_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_itunes_timestamps_agg_mean',
 'Cust_Agg_L2_fbb_fx_first_days_since_nif',
 'netscout_ns_apps_whatsapp_voice_calling_data_mb_agg_mean',
 'netscout_ns_apps_shopping_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_instagram_total_effective_ul_mb_agg_mean',
 'GNV_Voice_L2_total_mou_we_agg_mean',
 'netscout_ns_apps_amazon_days_agg_mean',
 'netscout_ns_apps_googledrive_timestamps_agg_mean',
 'netscout_ns_apps_finance_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_facebookmessages_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_amazon_data_mb_agg_mean',
 'netscout_ns_apps_youtube_data_mb_agg_mean',
 'Cust_Agg_num_tariff_xs',
 'netscout_ns_apps_facebook_video_days_agg_mean',
 'Cust_Agg_num_2lins',
 'netscout_ns_apps_apple_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_technology_timestamps_agg_mean',
 'Ord_sla_cambio_orders_last30',
 'GNV_Voice_L2_max_num_calls_WE_agg_mean',
 'Cust_Agg_L2_tv_fx_first_days_since_nif',
 'netscout_ns_apps_netflix_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_business_total_effective_dl_mb_agg_mean',
 'netscout_ns_apps_webgames_data_mb_agg_mean',
 'Cust_age',
 'Cust_Agg_mobile_services_nc',
 'GNV_Voice_L2_max_num_calls_W_agg_mean',
 'netscout_ns_apps_whatsapp_data_mb_agg_mean',
 'netscout_ns_apps_itunes_total_effective_ul_mb_agg_mean',
 'Ord_sla_ord_admin_last_order_last60',
 'netscout_ns_apps_web_vodafone_http_total_effective_ul_mb_agg_mean',
 'Cust_L2_migrated_client',
 'Ord_sla_ord_admin_first_order_last180',
 'netscout_ns_apps_booking_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_spotify_data_mb_agg_mean',
 'tgs_days_until_fecha_fin_dto_agg_mean',
 'netscout_ns_apps_gmail_total_effective_dl_mb_agg_mean',
 'netscout_ns_apps_gmail_timestamps_agg_mean',
 'Ord_sla_ord_admin_last_order_last90',
 'netscout_ns_apps_business_timestamps_agg_mean',
 'Cust_Agg_num_tariff_redm',
 'netscout_ns_apps_twitter_timestamps_agg_mean',
 'Order_Agg_Cambio_COM_orders',
 'netscout_ns_apps_facebook_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_adultweb_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_audio_timestamps_agg_mean',
 'Cust_Agg_num_tariff_smart',
 'netscout_ns_apps_googledrive_total_effective_dl_mb_agg_mean',
 'netscout_ns_apps_apple_total_effective_dl_mb_agg_mean',
 'netscout_ns_apps_spotify_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_samsung_timestamps_agg_mean',
 'Cust_Agg_num_tariff_minim',
 'Spinners_nif_port_freq_per_day',
 'netscout_ns_apps_gmail_total_effective_ul_mb_agg_mean',
 'Cust_Agg_num_tariff_plana200min',
 'netscout_ns_apps_web_vodafone_http_timestamps_agg_mean',
 'GNV_Voice_L2_total_mou_w_agg_mean',
 'netscout_ns_apps_webgames_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_twitter_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_amazon_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_webgames_timestamps_agg_mean',
 'Ord_sla_ord_admin_orders_last30',
 'netscout_ns_apps_googledrive_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_youtube_total_effective_ul_mb_agg_mean',
 'netscout_ns_apps_finance_timestamps_agg_mean',
 'netscout_ns_apps_adultweb_data_mb_agg_mean',
 'netscout_ns_apps_instagram_total_effective_dl_mb_agg_mean',
 'netscout_ns_apps_booking_timestamps_agg_mean',
 'netscout_ns_apps_netflix_timestamps_agg_mean',
 'netscout_ns_apps_samsung_data_mb_agg_mean',
 'tgs_sum_ind_under_use_agg_mean',
 'Penal_SRV_PENDING_N1_penal_amount_agg_mean',
 'netscout_ns_apps_news_total_effective_ul_mb_agg_mean']