# Horrible script to Remove variabes and impute NA's

CleanData <- function(dt.data) {
  
  dt.data[, ASIGNACION_COMERCIAL := as.factor(ASIGNACION_COMERCIAL)]
  
  dt.data[, c("IND_ACCESO_DIRECTO", "IND_ACCESO_FHC", "IND_ACCESO_FTTH", "IND_ACCESO_INDIRECTO") := NULL]
  dt.data[, c("IND_ACCESO_INTEGRADO", "IND_ADSL", "IND_ADSL_LISTANEGRA", "IND_ADSL_PERMANENCIA") := NULL]
  dt.data[, c("IND_ADSL_PROVISION", "IND_ADSL_SIN_FIJO", "IND_ADSL_UNICO") := NULL]
  dt.data[, c("IND_AGR_CANAL127", "IND_AGR_CANAL128", "IND_AGR_COLLECTION_AG", "IND_AGR_CONVERGENTE") := NULL]
  dt.data[, c("IND_AGR_DEVOLUCIONES", "IND_AGR_EMP_AGENTE", "IND_AGR_FOLLOWUP", "IND_AGR_IDIOMAS") := NULL]
  dt.data[, c("IND_AGR_POSP_AG", "IND_AGR_PREP_AG", "IND_AGR_SUPPORT_AGENTE", "IND_AGR_WINBACK") := NULL]
  dt.data[, c("IND_AGR_WINBACK_ARPU", "IND_AGR_WINBACK_SIMLOCK", "IND_ALTA_CLI", "IND_BROOKLYN") := NULL]
  
  dt.data[, c("IND_CLF_FIBRA", "IND_CORTES", "IND_CORTES_3M", "IND_DEGRADACION_SERV", "IND_DEGRADACION_SERV_3M") := NULL]
  dt.data[, c("IND_DSL_UNICO", "IND_FIBRA", "IND_FIJO_MOVIL_SINVOZ", "IND_FIJO_OFICINA_MOVIL", "IND_FIJO_TRADICIONAL") := NULL]
  
  dt.data[, IND_FTTH := NULL]
  dt.data[, IND_FUTBOL := NULL]
  
  if ("IND_FINAN_ACTIVAS" %in% colnames(dt.data)) {
    dt.data[, IND_FINAN_ACTIVAS := NULL]
  }
  
  if ("IND_FINAN_CANCELACIONES" %in% colnames(dt.data)) {
    dt.data[, IND_FINAN_CANCELACIONES := NULL]
    dt.data[, IND_FINAN_DEVOLUCIONES := NULL]
    dt.data[, IND_FINAN_ERRONEAS := NULL]
    dt.data[, IND_FINAN_FINALIZADAS := NULL]
    dt.data[, IND_FINAN_PENDIENTES := NULL]
  }
  
  dt.data[, IND_HEAD_COLLECTION := NULL]
  dt.data[, IND_HEAD_CONSUMER_SERVICE := NULL]
  dt.data[, IND_HEAD_ENTERPRISE_SER := NULL]
  dt.data[, IND_HEAD_TECHNICAL_SUP := NULL]
  dt.data[, IND_HEAD_WINBACK := NULL]
  dt.data[, IND_HFC := NULL]
  dt.data[, IND_INST := NULL]
  dt.data[, IND_INT_CENTRALITA := NULL]
  dt.data[, IND_INTEGRADO := NULL]
  dt.data[, IND_INT_NUBE := NULL]
  dt.data[, IND_INT_NUBE_CENTRALITA := NULL]
  
  dt.data[, c("IND_INT_TOTAL", "IND_IP_FIJA", "IND_L_COMPATIBLE", "IND_LLAMADA_LARGA", "IND_LLAM_ADSL") := NULL]
  dt.data[, c("IND_LLAM_ALTA", "IND_LLAM_BAJA", "IND_LLAM_COBROS", "IND_LLAM_ONO", "IND_LLAM_PORTABILIDAD") := NULL]
  
  dt.data[, c("IND_LLAM_RAZON_ABONOS", "IND_LLAM_RAZON_ACCESO", "IND_LLAM_RAZON_BAJOCONS", "IND_LLAM_RAZON_CAMBIO", "IND_LLAM_RAZON_CARGOS") := NULL]
  dt.data[, c("IND_LLAM_RAZON_CONSULTA", "IND_LLAM_RAZON_DATOS_CONSUMO", "IND_LLAM_RAZON_DESVIOS", "IND_LLAM_RAZON_GESTION", "IND_LLAM_RAZON_IMPORTE") := NULL]
  dt.data[, c("IND_LLAM_RAZON_OFERTA", "IND_LLAM_RAZON_PAGAR", "IND_LLAM_RAZON_PETICION", "IND_LLAM_RAZON_PRODUCTO", "IND_LLAM_RAZON_RESTRICIONES") := NULL]
  
  dt.data[, c("IND_LLAM_RAZON_PP", "IND_LLAM_RAZON_ROAMING", "IND_LLAM_RAZON_SMS_CONTESTADOR", "IND_LLAM_RAZON_TRAMITAR", "IND_LLAM_RESUL_ABONO") := NULL]
  dt.data[, c("IND_LLAM_RESUL_ABROCASO", "IND_LLAM_RESUL_ACT_DESAC", "IND_LLAM_RESUL_AYUDO", "IND_LLAM_RESUL_CIERRE", "IND_LLAM_RESUL_COMPLETADO") := NULL]
  dt.data[, c("IND_LLAM_RESUL_INCIDENCIA", "IND_LLAM_RESUL_INFORMAR", "IND_LLAM_RESUL_MODIF", "IND_LLAM_RESUL_PAGARA", "IND_LLAM_RESUL_PENSARA") := NULL]
  dt.data[, c("IND_LLAM_RESUL_TECNICO", "IND_LLAM_SAT", "IND_LLAM_SOPORTE", "IND_LLAM_SUBTIPO_ADSL", "IND_LLAM_SUBTIPO_AREACLI") := NULL]
  dt.data[, c("IND_LLAM_SUBTIPO_DEUDA", "IND_LLAM_SUBTIPO_DISPOSITIVO", "IND_LLAM_SUBTIPO_ERROR", "IND_LLAM_SUBTIPO_FIBRA", "IND_LLAM_SUBTIPO_FIJO") := NULL]
  
  dt.data[, c("IND_LLAM_SUBTIPO_IMEI", "IND_LLAM_SUBTIPO_INCOMUNICADO", "IND_LLAM_SUBTIPO_INFORMACION", "IND_LLAM_SUBTIPO_MOVIL", "IND_LLAM_SUBTIPO_NEGOCIACION") := NULL]
  dt.data[, c("IND_LLAM_SUBTIPO_POLITICA", "IND_LLAM_SUBTIPO_REPARACION", "IND_LLAM_SUBTIPO_ROUTER", "IND_LLAM_SUBTIPO_SIM", "IND_LLAM_SUBTIPO_TITULAR") := NULL]
  dt.data[, c("IND_LLAM_VIA_CLIENTE_AUTOR", "IND_LLAM_VIA_DISTRIBUIDOR", "IND_LLAM_VIA_LLAMADA", "IND_LLAM_VIA_SMS", "IND_LLAM_VIA_TRANSFERIDA") := NULL]
  
  dt.data[, IND_MANHATTAN := NULL]
  dt.data[, IND_NIVEL_AVANT := NULL]
  dt.data[, IND_NIVEL_AVANT_AUTONOMOS := NULL]
  dt.data[, IND_NIVEL_DIAMANTE := NULL]
  dt.data[, IND_NIVEL_DISTRIBUIDORES := NULL]
  
  dt.data[,  c("IND_PROMO_FUTBOL_BAR", "IND_PROMO_LIGA", "IND_PROMO_LIGA_BAR", "IND_PROMO_LIGA_COPA", "IND_PROMO_TV_BAR", "IND_PROVISION", "IND_PUNT_AGENTE_ALTA")  := NULL]
  
  dt.data[, c("IND_NIVEL_ORO", "IND_NIVEL_PLATINO","IND_NIVEL_PLATINO_AUTONOMOS", "IND_NIVEL_PREMIUM_AUTONOMOS", "IND_NIVEL_PREMIUM_E", "IND_NIVEL_PRO",   "IND_NIVEL_PRO_AUTONOMOS", "IND_NIVEL_SIN_NDS"
  ) := NULL]
  
  dt.data[, c("IND_SERV_ALWAYSSOLVED","IND_SERV_BAJAS",  "IND_SERV_CANAL127", "IND_SERV_CANAL128", "IND_SERV_COBROS", "IND_SERV_CONSERV_ARPU", "IND_SERV_CONTROL_CUENTAS"
  ) := NULL]
  
  dt.data[, c("IND_NIVEL_VODAFONE", "IND_NUEVO_STACK", "IND_OMNIA", "IND_OMNIA_CABECERA", "IND_ORIGEN_CLF_ADSL", "IND_ORIGEN_SBL_ADSL", "IND_ORIGEN_SBL_FIBRA") := NULL ]
  
  dt.data[, c("IND_SERV_CONVERGENTE", "IND_SERV_DATOS",  "IND_SERV_DEVOLUCIONES", "IND_SERV_DIAMANTE", "IND_SERV_EMISION", "IND_SERV_EMPRESAS", 
              "IND_SERV_GOLD","IND_SERV_HD") := NULL]
  
  dt.data[, c("IND_SERV_HFC",  "IND_SERV_IDIOMAS", "IND_SERV_PLATINO", "IND_SERV_PORTABILIDAD", "IND_SERV_PREMIUM", "IND_SERV_PREPAGO", 
              "IND_SERV_PYMES",   "IND_SERV_SEC",   "IND_SERV_SILVER") := NULL ]
  
  dt.data[, c("IND_VALOR_AGENTE_ALTO", "IND_VALOR_AGENTE_BAJO", "IND_VALOR_AGENTE_MEDIO", "IND_VALOR_VF_ALTO", "IND_VALOR_VF_BAJO", "IND_VALOR_VF_MEDIO",
              "IND_VDSL") :=NULL]
  
  dt.data[, c("IND_PUNT_GLOBAL_ALTA", "IND_PUNT_VF_ALTA", "IND_SENTIDO_CONSULTA", "IND_SENTIDO_ENTRADA", "IND_SENTIDO_SALIDA") := NULL]
  
  
  dt.data[, c("IND_TIPO_GT_EMP_OUT","IND_TIPO_GT_EMPRESAS","IND_TIPO_GT_PART","IND_TIPO_GT_PART_OUT", "IND_TV_PUBLICA",  "IND_VEL_MENOR_50") := NULL]
  
  dt.data[, c("IND_VEL_MENOR_50_3M", "NUM_ACCESO_DIRECTO", "NUM_ACCESO_FHC", "NUM_ACCESO_FTTH", "NUM_ACCESO_INDIRECTO", "NUM_ACCESO_INTEGRADO") := NULL]
  
  dt.data[, c("NUM_ADSL", "NUM_ADSL_SIN_FIJO", "NUM_ADSL_UNICO") := NULL]
  
  dt.data[, c("NUM_AVG_MAX_VEL_DOWN_ALCAN_3M", "NUM_AVG_MEJOR_VEL_DOWN_3M", "NUM_AVG_MEJOR_VEL_UP_3M", "NUM_AVG_TIME_FACTURACION", "NUM_AVG_TIME_FIJO") := NULL]
  
  dt.data[is.na(NUM_ARPU_DATOS_AVG_LIN), NUM_ARPU_DATOS_AVG_LIN := -1]
  dt.data[is.na(NUM_ARPU_DATOS_M0), NUM_ARPU_DATOS_M0 := -1]
  dt.data[is.na(NUM_ARPU_NOVOZ_M0), NUM_ARPU_NOVOZ_M0 := -1]
  dt.data[is.na(NUM_ARPU_TOT_M0), NUM_ARPU_TOT_M0 := -1]
  dt.data[is.na(NUM_ARPU_VOZ_AVG_LIN), NUM_ARPU_VOZ_AVG_LIN := -1]
  dt.data[is.na(NUM_ARPU_VOZ_M0), NUM_ARPU_VOZ_M0 := -1]
  dt.data[, c("NUM_AVG_TIME_MOVIL", "NUM_AVG_TIME_RESTO", "NUM_AVG_TIME_VODAFONE", "NUM_AVG_VEL_DOWN_ACTUAL_3M", "NUM_AVG_VEL_UP_ACTUAL_3M", "NUM_BROOKLYN") := NULL]
  
  if ("NUM_CANTIDAD_FINANCIADA_MAX" %in% colnames(dt.data)) {
    dt.data[, NUM_CANTIDAD_FINANCIADA_MAX := NULL]
    dt.data[, NUM_CANTIDAD_FINANCIADA_MIN := NULL]
    dt.data[, NUM_CUOTAS_PAGADAS_MAX := NULL]
    dt.data[, NUM_CUOTAS_PAGADAS_MIN := NULL]
    dt.data[, NUM_CUOTAS_PENDIENTES_MAX := NULL]
    dt.data[, NUM_CUOTAS_PENDIENTES_MIN := NULL]
    dt.data[, NUM_CUOTAS_TOT_MAX := NULL]
    dt.data[, NUM_CUOTAS_TOT_MIN := NULL]
  }
  
  dt.data[, c("NUM_DIF_AVG_MAX_ROUT_CONTR_3M", "NUM_DIF_AVG_MAX_ROUTER_ACTU_3M", "NUM_DIF_AVG_MAX_ROUTER_SERV_3M", "NUM_DIF_AVG_SERV_ACTUAL_SUB_3M", "NUM_DIF_AVG_SERV_ACTUAL_3M") := NULL]
  dt.data[, c("NUM_DIF_AVG_VEL_DOWN_ACTUAL_3M", "NUM_DIF_MAX_MEJ_VEL_D_SERV_3M", "NUM_DIF_MAX_ROUT_CONTRATADA_3M", "NUM_DIF_MAX_ROUTER_ACTU") := NULL]
  dt.data[, c("NUM_DIF_MAX_ROUTER_ACTU_3M","NUM_DIF_MAX_ROUTER_CONTRATADA", "NUM_DIF_MAX_ROUTER_SERV", "NUM_DIF_MAX_ROUTER_SERV_3M", "NUM_DIF_MAX_SERV_ACTUAL_SUB_3M") := NULL]
  dt.data[, c("NUM_DIF_MAX_SERV_ACTUAL_3M", "NUM_DIF_MAX_VEL_DOWN_ACTUAL_3M", "NUM_DIF_MEJOR_VEL_DOWN_SERV", "NUM_DIF_MEJOR_VEL_DOWN_SERV_3M") := NULL]
  dt.data[, c("NUM_DIF_MIN_MAX_MEJ_VEL_D_S_3M", "NUM_DIF_MIN_MAX_ROUT_CONT_3M", "NUM_DIF_MIN_MAX_ROUTER_ACTU_3M", "NUM_DIF_MIN_MAX_ROUTER_SERV_3M", "NUM_DIF_MIN_SERV_ACTUAL_SUB_3M") := NULL]
  
  dt.data[, c("NUM_DIF_MIN_SERV_ACTUAL_3M","NUM_DIF_MIN_VEL_DOWN_ACTUAL_3M", "NUM_DIF_SERV_ACTUAL", "NUM_DIF_SERV_ACTUAL_SUBIDA", "NUM_DIF_VEL_DOWN_ACTUAL") := NULL]
  
  dt.data[is.na(NUM_DISP_ANDROID_M0), NUM_DISP_ANDROID_M0 := 0]
  dt.data[is.na(NUM_DISP_BB_M0), NUM_DISP_BB_M0 := 0]
  dt.data[is.na(NUM_DISP_IOS_INC), NUM_DISP_IOS_INC := 0]
  dt.data[is.na(NUM_DISP_IOS_M0), NUM_DISP_IOS_M0 := 0]
  dt.data[is.na(NUM_DISP_MOVIL_INC), NUM_DISP_MOVIL_INC := 0]
  dt.data[is.na(NUM_DISP_MOVIL_M0), NUM_DISP_MOVIL_M0 := 0]
  
  dt.data[is.na(NUM_DISP_NO_MOVIL_M0), NUM_DISP_NO_MOVIL_M0 := 0]
  dt.data[is.na(NUM_DISPOSITIVOS_INC), NUM_DISPOSITIVOS_INC := 0]
  dt.data[is.na(NUM_DISPOSITIVOS_M0), NUM_DISPOSITIVOS_M0 := 0]
  dt.data[, NUM_DSL_UNICO := NULL]
  dt.data[is.na(NUM_EMPLEADOS), NUM_EMPLEADOS := 0]
  
  dt.data[is.na(NUM_ENT_LLAM_DIST_TOT), NUM_ENT_LLAM_DIST_TOT := 0]
  dt.data[is.na(NUM_ENT_LLAM_DIST_TOT_INC), NUM_ENT_LLAM_DIST_TOT_INC := 0]
  dt.data[is.na(NUM_ENT_LLAM_TOT), NUM_ENT_LLAM_TOT := 0]
  dt.data[is.na(NUM_ENT_LLAM_TOT_INC), NUM_ENT_LLAM_TOT_INC := 0]
  dt.data[is.na(NUM_ENT_MIN_TOT), NUM_ENT_MIN_TOT := 0]
  dt.data[is.na(NUM_ENT_MIN_TOT_INC), NUM_ENT_MIN_TOT_INC := 0]
  dt.data[is.na(NUM_ENT_MIN_TOT), NUM_ENT_MIN_TOT := 0]
  dt.data[is.na(NUM_ENT_MIN_TOT_INC), NUM_ENT_MIN_TOT_INC := 0]
  dt.data[is.na(NUM_ENT_SMS_DIST_TOT), NUM_ENT_SMS_DIST_TOT := 0]
  dt.data[is.na(NUM_ENT_SMS_DIST_TOT_INC), NUM_ENT_SMS_DIST_TOT_INC := 0]
  dt.data[is.na(NUM_ENT_SMS_TOT), NUM_ENT_SMS_TOT := 0]
  dt.data[is.na(NUM_ENT_SMS_TOT_INC), NUM_ENT_SMS_TOT_INC := 0]
  dt.data[, NUM_FIJO_MOVIL_SINVOZ := NULL]
  dt.data[, NUM_FIJO_TRADICIONAL := NULL]
  
  if ("NUM_FINAN_ACTIVAS" %in% colnames(dt.data)) {
    dt.data[, NUM_FINAN_ACTIVAS := NULL]
    dt.data[, NUM_FINANCIACIONES_HIST := NULL]
    dt.data[, NUM_FINANCIACION_TOTAL := NULL]
  }
  
  dt.data[, NUM_FINAN_CANCELACIONES := NULL]
  
  dt.data[, c("NUM_MANHATTAN", "NUM_FINAN_DEVOLUCIONES", "NUM_FINAN_ERRONEAS", "NUM_FINAN_FINALIZADAS", "NUM_FINAN_PENDIENTES") := NULL]
  dt.data[, c("NUM_IND_STACK", "NUM_INST", "NUM_INT_CENTRALITA", "NUM_INTEGRADO", "NUM_INT_NUBE", "NUM_INT_NUBE_CENTRALITA") := NULL]
  
  dt.data[, c("NUM_MAX_MEJOR_VEL_DOWN_3M", "NUM_MAX_MEJOR_VEL_UP_3M", "NUM_MAX_MIN_VEL_DOWN_ALCAN_3M", "NUM_MAX_PUNT_GLOBAL", "NUM_MAX_PUNT_GLOBAL_DIF") := NULL]
  dt.data[, c("NUM_MAX_VEL_DOWN_ACTUAL_3M", "NUM_MAX_VEL_DOWN_ALCAN", "NUM_MAX_VEL_DOWN_ALCAN_3M",  "NUM_MAX_VEL_UP_ACTUAL_3M", "NUM_MEJOR_MIN_VEL_DOWN_3M") := NULL]
  dt.data[, c("NUM_MEJOR_MIN_VEL_UP_3M", "NUM_MEJOR_VEL_DOWN", "NUM_MEJOR_VEL_UP", "NUM_MESES_FIN_FINANCIACION_MAX", "NUM_MESES_FIN_FINANCIACION_MIN") := NULL]
  
  if ("NUM_IMPORTE_PAGADO_MAX" %in% colnames(dt.data)) {
    dt.data[, NUM_IMPORTE_PAGADO_MAX := NULL]
    dt.data[, NUM_IMPORTE_PAGADO_MIN := NULL]
    dt.data[, NUM_IMPORTE_RESTANTE_MAX := NULL]
    dt.data[, NUM_IMPORTE_RESTANTE_MIN := NULL]
    
    dt.data[, NUM_IMP_PEND_MAX := NULL]
    dt.data[, NUM_IMP_TOTAL_PEND := NULL]
  }
  
  dt.data[, NUM_INT_TOTAL := NULL]
  dt.data[, NUM_IP_FIJA := NULL]
  dt.data[, NUM_KB_DATOS_M0 := NULL]
  dt.data[, NUM_L_COMPATIBLE := NULL]
  dt.data[is.na(NUM_KB_ROAMING_M0), NUM_KB_ROAMING_M0 := -1]
  dt.data[is.na(NUM_LINEAS_VOZ_M0), NUM_LINEAS_VOZ_M0 := 0]
  dt.data[, NUM_OMNIA_CABECERA := NULL]
  dt.data[is.na(NUM_MIN_INTER_M0), NUM_MIN_INTER_M0 := -1]
  dt.data[is.na(NUM_MIN_INTER_INC), NUM_MIN_INTER_INC := -1]
  dt.data[is.na(NUM_MULTIDISP), NUM_MULTIDISP := -1]
  dt.data[is.na(NUM_NOTEBOOK_M0), NUM_NOTEBOOK_M0 := -1]
  
  dt.data[,  c("NUM_PROVISION","NUM_PUNT_AGENTE","NUM_PUNT_GLOBAL",  "NUM_PUNT_GLOBAL_ALTA", "NUM_PUNT_GLOBAL_DIF",  "NUM_PUNT_VF") := NULL ]
  dt.data[is.na(NUM_CAR_PHONE_M0), NUM_CAR_PHONE_M0 := -1]
  dt.data[, NUM_CLF_FIBRA := NULL]
  dt.data[, MES := NULL] 
  dt.data[, NUM_FIBRA := NULL]
  dt.data[, NUM_FTTH := NULL]
  dt.data[, NUM_HFC := NULL]
  
  dt.data[, NUM_VDSL := NULL]
  
  #dt.data[is.na(NUM_OMNIA), NUM_OMNIA := -1]
  dt.data[, c("NUM_ORIGEN_CLF_ADSL", "NUM_ORIGEN_SBL_ADSL", "NUM_ORIGEN_SBL_FIBRA") := NULL]
  
  if ("NUM_PCT_FINAN_ACTIVAS" %in% colnames(dt.data)) {
    dt.data[is.na(NUM_PCT_FINAN_ACTIVAS), NUM_PCT_FINAN_ACTIVAS := -1]
  }
  dt.data[, c("NUM_PCT_FINAN_CANCELACIONES", "NUM_PCT_FINAN_DEVOLUCIONES", "NUM_PCT_FINAN_ERRONEAS", "NUM_PCT_FINAN_FINALIZADAS") := NULL]
  dt.data[, NUM_PCT_FINAN_PENDIENTES := NULL]
  dt.data[is.na(NUM_PCT_HBD_LIN_VOZ), NUM_PCT_HBD_LIN_VOZ := -1]
  
  if ("NUM_PCT_IMPORTE_PAGADO_MAX" %in% colnames(dt.data)) {
    dt.data[, NUM_PCT_IMPORTE_PAGADO_MAX := NULL]
    dt.data[, NUM_PCT_IMPORTE_PAGADO_MIN := NULL]
    dt.data[, NUM_PCT_IMPORTE_RESTANTE_MAX := NULL]
    dt.data[, NUM_PCT_IMPORTE_RESTANTE_MIN := NULL]
  }
  dt.data[is.na(NUM_PCT_LPD_LIN_VOZ), NUM_PCT_LPD_LIN_VOZ := -1]
  dt.data[is.na(NUM_SAL_LLAM_DIST_MV), NUM_SAL_LLAM_DIST_MV := 0]
  dt.data[is.na(NUM_SAL_LLAM_DIST_MV_INC), NUM_SAL_LLAM_DIST_MV_INC := 0]
  
  dt.data[, NUM_SAL_LLAM_DIST_OG := NULL] # FIXME all 1's
  dt.data[, NUM_SAL_LLAM_DIST_OG_INC := NULL] # FIXME all 0's
  dt.data[, NUM_SAL_LLAM_OG_INC := NULL] # FIXME
  dt.data[, NUM_SAL_MIN_OG_INC := NULL] # FIXME
  
  dt.data[is.na(NUM_SAL_LLAM_DIST_RE), NUM_SAL_LLAM_DIST_RE := 0]
  dt.data[is.na(NUM_SAL_LLAM_DIST_RE_INC), NUM_SAL_LLAM_DIST_RE_INC := 0]
  dt.data[is.na(NUM_SAL_LLAM_DIST_TOT), NUM_SAL_LLAM_DIST_TOT := 0]
  dt.data[is.na(NUM_SAL_LLAM_DIST_TOT_INC), NUM_SAL_LLAM_DIST_TOT_INC := 0]
  dt.data[is.na(NUM_SAL_LLAM_DIST_VF), NUM_SAL_LLAM_DIST_VF := 0]
  dt.data[is.na(NUM_SAL_LLAM_DIST_VF_INC), NUM_SAL_LLAM_DIST_VF_INC := 0]
  
  dt.data[is.na(NUM_SAL_LLAM_DIST_YO), NUM_SAL_LLAM_DIST_YO := 0]
  dt.data[is.na(NUM_SAL_LLAM_DIST_YO_INC), NUM_SAL_LLAM_DIST_YO_INC := 0]
  dt.data[is.na(NUM_SAL_LLAM_MV), NUM_SAL_LLAM_MV := 0]
  dt.data[is.na(NUM_SAL_LLAM_MV_INC), NUM_SAL_LLAM_MV_INC := 0]
  dt.data[is.na(NUM_SAL_LLAM_OG), NUM_SAL_LLAM_OG := 0]
  dt.data[is.na(NUM_SAL_LLAM_RE), NUM_SAL_LLAM_RE := -1]
  dt.data[is.na(NUM_SAL_LLAM_RE_INC), NUM_SAL_LLAM_RE_INC := 0]
  dt.data[is.na(NUM_SAL_LLAM_TOT), NUM_SAL_LLAM_TOT := 0]
  dt.data[is.na(NUM_SAL_LLAM_TOT_INC), NUM_SAL_LLAM_TOT_INC := 0]
  dt.data[is.na(NUM_SAL_LLAM_VF), NUM_SAL_LLAM_VF := 0]
  
  dt.data[is.na(NUM_SAL_LLAM_VF_INC), NUM_SAL_LLAM_VF_INC := 0]
  dt.data[is.na(NUM_SAL_LLAM_YO), NUM_SAL_LLAM_YO := 0]
  dt.data[is.na(NUM_SAL_LLAM_YO_INC), NUM_SAL_LLAM_YO_INC := 0]
  dt.data[is.na(NUM_SAL_MIN_MV), NUM_SAL_MIN_MV := 0]
  dt.data[is.na(NUM_SAL_MIN_MV_INC), NUM_SAL_MIN_MV_INC := 0]
  dt.data[is.na(NUM_SAL_MIN_OG), NUM_SAL_MIN_OG := 0]
  dt.data[is.na(NUM_SAL_MIN_RE), NUM_SAL_MIN_RE := 0]
  dt.data[is.na(NUM_SAL_MIN_RE_INC), NUM_SAL_MIN_RE_INC := 0]
  dt.data[is.na(NUM_SAL_MIN_TOT), NUM_SAL_MIN_TOT := 0]
  dt.data[is.na(NUM_SAL_MIN_TOT_INC), NUM_SAL_MIN_TOT_INC := 0]
  dt.data[is.na(NUM_SAL_MIN_VF), NUM_SAL_MIN_VF := 0]
  dt.data[is.na(NUM_SAL_MIN_VF_INC), NUM_SAL_MIN_VF_INC := 0]
  dt.data[is.na(NUM_SAL_MIN_YO), NUM_SAL_MIN_YO := 0]
  
  dt.data[is.na(NUM_SAL_MIN_YO_INC), NUM_SAL_MIN_YO_INC := 0]
  dt.data[is.na(NUM_SAL_SMS_DIST_TOT), NUM_SAL_SMS_DIST_TOT := 0]
  dt.data[is.na(NUM_SAL_SMS_DIST_TOT_INC), NUM_SAL_SMS_DIST_TOT_INC := 0]
  dt.data[is.na(NUM_SAL_SMS_TOT), NUM_SAL_SMS_TOT := 0]
  dt.data[is.na(NUM_SAL_SMS_TOT_INC), NUM_SAL_SMS_TOT_INC := 0]
  
  dt.data[is.na(NUM_TABLET_M0), NUM_TABLET_M0 := -1]
  dt.data[is.na(NUM_SAL_SMS_DIST_TOT), NUM_SAL_SMS_DIST_TOT := -1]
  dt.data[, NUM_USAC_ADSL := NULL]     
  dt.data[, NUM_USAC_ADSL_M2 := NULL]
  
  dt.data[, c("NUM_VEL_MIN_DOWN_ACTUAL_3M", "NUM_VEL_MIN_UP_ACTUAL_3M", "NUM_VELOCIDAD", "NUM_VELOCIDAD_AVG", "NUM_VEL_UP_ACTUAL", "NUM_VEL_DOWN_ACTUAL") := NULL]
  
  dt.data[is.na(NUM_USAC_ALTA), NUM_USAC_ALTA := -1]     
  dt.data[is.na(NUM_USAC_ALTA_M2), NUM_USAC_ALTA_M2 := -1]
  dt.data[is.na(NUM_USAC_CANCELACION), NUM_USAC_CANCELACION := -1]
  dt.data[is.na(NUM_USAC_CANCELACION_M2), NUM_USAC_CANCELACION_M2 := -1]
  dt.data[is.na(NUM_USAC_ECONOMICO), NUM_USAC_ECONOMICO := -1]
  dt.data[is.na(NUM_USAC_ECONOMICO_M2), NUM_USAC_ECONOMICO_M2 := -1]
  dt.data[is.na(NUM_USAC_INFO), NUM_USAC_INFO := -1]
  dt.data[is.na(NUM_USAC_INFO_M2), NUM_USAC_INFO_M2 := -1]
  dt.data[is.na(NUM_USAC_KO), NUM_USAC_KO := -1]
  dt.data[is.na(NUM_USAC_KO), NUM_USAC_KO_M2 := -1]
  dt.data[is.na(NUM_USAC_KOS), NUM_USAC_KOS := -1]
  dt.data[is.na(NUM_USAC_KOS_M2), NUM_USAC_KOS_M2 := -1]
  dt.data[is.na(NUM_USAC_LLAMADA), NUM_USAC_LLAMADA := -1]
  dt.data[is.na(NUM_USAC_LLAMADA_M2), NUM_USAC_LLAMADA_M2 := -1]
  dt.data[is.na(NUM_USAC_LLAMADA_VALIDA), NUM_USAC_LLAMADA_VALIDA := -1]
  dt.data[is.na(NUM_USAC_LLAMADA_VALIDA_M2), NUM_USAC_LLAMADA_VALIDA_M2 := -1]
  dt.data[is.na(NUM_USAC_MIGRACION), NUM_USAC_MIGRACION := -1]
  dt.data[is.na(NUM_USAC_MIGRACION_M2), NUM_USAC_MIGRACION_M2 := -1]
  dt.data[is.na(NUM_USAC_OK), NUM_USAC_OK := -1]
  dt.data[is.na(NUM_USAC_OK_M2), NUM_USAC_OK_M2 := -1]
  dt.data[is.na(NUM_USAC_PAGOS), NUM_USAC_PAGOS := -1]
  dt.data[is.na(NUM_USAC_PAGOS_M2), NUM_USAC_PAGOS_M2 := -1]
  dt.data[is.na(NUM_USAC_PENDIENTE), NUM_USAC_PENDIENTE := -1]
  dt.data[is.na(NUM_USAC_PENDIENTE_M2), NUM_USAC_PENDIENTE_M2 := -1]
  dt.data[is.na(NUM_USAC_PERMANENCIA), NUM_USAC_PERMANENCIA := -1]
  dt.data[is.na(NUM_USAC_PERMANENCIA_M2), NUM_USAC_PERMANENCIA_M2 := -1]
  dt.data[is.na(NUM_USAC_PORTAB), NUM_USAC_PORTAB := -1]
  dt.data[is.na(NUM_USAC_PORTABILIDAD), NUM_USAC_PORTABILIDAD := -1]
  dt.data[is.na(NUM_USAC_PORTABILIDAD_M2), NUM_USAC_PORTABILIDAD_M2 := -1]
  dt.data[is.na(NUM_USAC_PORTAB_M2), NUM_USAC_PORTAB_M2 := -1]
  dt.data[is.na(NUM_USAC_PROBS_SERVS), NUM_USAC_PROBS_SERVS := -1]
  dt.data[is.na(NUM_USAC_PROBS_SERVS_M2), NUM_USAC_PROBS_SERVS_M2 := -1]
  dt.data[is.na(NUM_USAC_PROD_SERV), NUM_USAC_PROD_SERV := -1]
  dt.data[is.na(NUM_USAC_PROD_SERV_M2), NUM_USAC_PROD_SERV_M2 := -1]
  dt.data[is.na(NUM_USAC_PRODS_SERVS), NUM_USAC_PRODS_SERVS := -1]
  dt.data[is.na(NUM_USAC_PRODS_SERVS_FIX), NUM_USAC_PRODS_SERVS_FIX := -1]
  dt.data[is.na(NUM_USAC_PRODS_SERVS_FIX_M2), NUM_USAC_PRODS_SERVS_FIX_M2 := -1]
  dt.data[is.na(NUM_USAC_PRODS_SERVS_MOVS), NUM_USAC_PRODS_SERVS_MOVS := -1]
  dt.data[is.na(NUM_USAC_PRODS_SERVS_MOVS_M2), NUM_USAC_PRODS_SERVS_MOVS_M2 := -1]
  dt.data[is.na(NUM_USAC_PRODS_SERVS_M2), NUM_USAC_PRODS_SERVS_M2 := -1]
  dt.data[is.na(NUM_USAC_PROMOCIONES), NUM_USAC_PROMOCIONES := -1]
  dt.data[is.na(NUM_USAC_PROMOCIONES_M2), NUM_USAC_PROMOCIONES_M2 := -1]
  dt.data[is.na(NUM_USAC_SERV_TECNICO), NUM_USAC_SERV_TECNICO := -1]
  dt.data[is.na(NUM_USAC_SERV_TECNICO_M2), NUM_USAC_SERV_TECNICO_M2 := -1]
  dt.data[is.na(NUM_USAC_TARIFAS), NUM_USAC_TARIFAS := -1]
  dt.data[is.na(NUM_USAC_TARIFAS_M2), NUM_USAC_TARIFAS_M2 := -1]
  dt.data[is.na(NUM_USAC_TARIFS), NUM_USAC_TARIFS := -1]
  dt.data[is.na(NUM_USAC_TARIFS_M2), NUM_USAC_TARIFS_M2 := -1]
  dt.data[is.na(NUM_USAC_VFCASA), NUM_USAC_VFCASA := -1]
  dt.data[is.na(NUM_USAC_VFCASA_M2), NUM_USAC_VFCASA_M2 := -1]
  dt.data[is.na(NUM_USAC_VOZ), NUM_USAC_VOZ := -1]    
  dt.data[is.na(NUM_USAC_VOZ_M2), NUM_USAC_VOZ_M2 := -1]
  
  if ("NUM_CUOTA_MENSUAL_MAX" %in% colnames(dt.data)) {
    dt.data[, NUM_CUOTA_MENSUAL_MAX := NULL]
    dt.data[, NUM_CUOTA_MENSUAL_MIN := NULL]
  }
  dt.data[is.na(NUM_USAC_DESACTIVACION), NUM_USAC_DESACTIVACION := 0]
  dt.data[is.na(NUM_USAC_DESACTIVACION_M2), NUM_USAC_DESACTIVACION_M2 := 0]
  dt.data[is.na(NUM_USAC_DEUDA), NUM_USAC_DEUDA := 0]
  dt.data[is.na(NUM_USAC_DEUDA_M2), NUM_USAC_DEUDA_M2 := 0]
  dt.data[is.na(NUM_USAC_DSL), NUM_USAC_DSL := 0]
  dt.data[is.na(NUM_USAC_DSL_M2), NUM_USAC_DSL_M2 := 0]
  
  dt.data[, SEG_ADSL_TIPO := NULL]
  dt.data[, SEG_NUM_ADSL := NULL]
  dt.data[, SEG_NUM_FIJOPORTADO := NULL]
  dt.data[, SEG_NUM_HHBD := NULL]
  dt.data[, SEG_NUM_LPD := NULL]
  dt.data[, SEG_SECTOR_ACT := as.factor(SEG_SECTOR_ACT)]
  dt.data[, SEG_SEGMENTO_MERCADO := as.factor(SEG_SEGMENTO_MERCADO)]
  dt.data[, SEG_TIPO_CIFNIF := NULL]
  
  dt.data[, NUM_PCT_ADSL_LINEAS := NULL]
  dt.data[, NUM_OMNIA := NULL]
  dt.data[, IND_TV := NULL]
  
  dt.data[, NUM_NOTEBOOK_AVG := NULL]
  dt.data[, NUM_NOTEBOOK_INC := NULL]
  dt.data[, NUM_CAR_PHONE_INC := NULL]
  if ("NUM_ADSL_INC" %in% colnames(dt.data))
    dt.data[, NUM_ADSL_INC := NULL]
  if ("SEG_TIPO_TV" %in% colnames(dt.data))
    dt.data[, SEG_TIPO_TV := NULL]
  
  # We remove it since it may be a proxy variable
  dt.data[, IND_FIJOPORTADO := NULL]
  dt.data[, NUM_FIJOPORTADO_INC := NULL]
  
  # Filter those variables related to customer interactions (it may be a proxy of a customer acquiring DSL/Fiber)
  usac.names <- colnames(dt.data)[colnames(dt.data) %like% "USAC"]
  dt.data <- dt.data[,!usac.names, with = F]
  arpu.no.voz <- c("NUM_ARPU_NOVOZ_M0", "NUM_ARPU_NOVOZ_INC", "NUM_ARPU_NOVOZ_AVG")
  
  dt.data <- dt.data[,!arpu.no.voz, with = F]
  dt.data[, NUM_FIJOPORTADO := NULL]
  dt.data[, NUM_ANTIGUEDAD_TV_MAX := NULL]
  dt.data[, NUM_ANTIGUEDAD_TV_MIN := NULL]
  dt.data[, c("IND_USO_TV_ADSL_M0", "IND_USO_TV_ADSL_3M"):= NULL]
  dt.data[, c("IND_FIJO_3M", "IND_FIJO_1M", "NUM_CONSUMO_TV", "NUM_CONSUMO_TV_AVG", "NUM_CONSUMO_TV_INC")  := NULL]
  dt.data[, c("NUM_FIJO_1M", "NUM_FIJO_3M") := NULL]
  
return(dt.data)
}
